SELECT 
    A.AUTHOR_ID, 
    A.AUTHOR_NAME,
    B.CATEGORY,
    SUM(BS.SALES * B.PRICE) AS TOTAL_SALES
FROM BOOK AS B
JOIN AUTHOR AS A
    ON B.AUTHOR_ID = A.AUTHOR_ID
JOIN BOOK_SALES AS BS
    ON B.BOOK_ID = BS.BOOK_ID 
WHERE DATE_FORMAT(BS.SALES_DATE, '%Y-%m') = '2022-01'
GROUP BY B.CATEGORY, A.AUTHOR_ID, A.AUTHOR_NAME
ORDER BY A.AUTHOR_ID ASC, B.CATEGORY DESC