SELECT AIN.ANIMAL_ID, AIN.ANIMAL_TYPE, AIN.NAME
FROM ANIMAL_INS AS AIN
JOIN ANIMAL_OUTS AS AOUT
ON AIN.ANIMAL_ID = AOUT.ANIMAL_ID
WHERE AIN.SEX_UPON_INTAKE IN ("Intact Male", "Intact Female")
AND AOUT.SEX_UPON_OUTCOME IN ("Neutered Male", "Spayed Female")
ORDER BY AIN.ANIMAL_ID;