# (방법 1) 서브쿼리
SELECT AIN.NAME, AIN.DATETIME
FROM ANIMAL_INS AS AIN
WHERE AIN.ANIMAL_ID NOT IN (
    SELECT AOUT.ANIMAL_ID FROM ANIMAL_OUTS AS AOUT
)
ORDER BY AIN.DATETIME
LIMIT 3;

# (방법 2) JOIN
SELECT AIN.NAME, AIN.DATETIME
FROM ANIMAL_INS AS AIN
LEFT JOIN ANIMAL_OUTS AS AOUT
ON AIN.ANIMAL_ID = AOUT.ANIMAL_ID
WHERE AOUT.ANIMAL_ID IS NULL
ORDER BY AIN.DATETIME
LIMIT 3;
