SELECT 
    BOARD.WRITER_ID AS USER_ID,
    USERS.NICKNAME ,
    SUM(BOARD.PRICE) AS TOTAL_SALES
    
FROM USED_GOODS_BOARD AS BOARD
JOIN USED_GOODS_USER AS USERS
ON BOARD.WRITER_ID = USERS.USER_ID
WHERE BOARD.STATUS = 'DONE'
GROUP BY BOARD.WRITER_ID
HAVING SUM(BOARD.PRICE) >= 700000
ORDER BY SUM(BOARD.PRICE) ASC