SELECT
    EMPLO.EMP_NO,
    EMPLO.EMP_NAME,
    CASE
        WHEN AVG(GRADE.SCORE) >= 96 THEN 'S' 
        WHEN AVG(GRADE.SCORE) >= 90 THEN 'A' 
        WHEN AVG(GRADE.SCORE) >= 80 THEN 'B' 
        ELSE 'C' 
    END AS GRADE,
    
    CASE
        WHEN AVG(GRADE.SCORE) >= 96 THEN EMPLO.SAL * 0.2
        WHEN AVG(GRADE.SCORE) >= 90 THEN EMPLO.SAL * 0.15
        WHEN AVG(GRADE.SCORE) >= 80 THEN EMPLO.SAL * 0.1
        ELSE EMPLO.SAL * 0
    END AS BONUS
    
FROM HR_EMPLOYEES AS EMPLO
JOIN HR_GRADE AS GRADE
    ON EMPLO.EMP_NO = GRADE.EMP_NO

GROUP BY EMPLO.EMP_NO
ORDER BY EMPLO.EMP_NO ASC