SELECT
    DEPA.DEPT_ID,
    DEPA.DEPT_NAME_EN,
    ROUND(AVG(EMP.SAL)) AS AVG_SAL
    
FROM HR_DEPARTMENT AS DEPA
JOIN HR_EMPLOYEES AS EMP
ON DEPA.DEPT_ID = EMP.DEPT_ID
GROUP BY DEPA.DEPT_ID
ORDER BY AVG(EMP.SAL) DESC
